package ru.taleworldsmp.shop;

import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;
import java.lang.reflect.Method;
import java.util.*;

public final class TaleWorldTelixShop extends JavaPlugin implements Listener, CommandExecutor {
    private Object manager; private Method get, remove, add;
    private final Map<UUID,String> pages = new HashMap<>();
    public void onEnable(){ saveDefaultConfig(); if(!hook()){getLogger().severe("TaleWorldSMP CurrencyManager not found");getServer().getPluginManager().disablePlugin(this);return;} getServer().getPluginManager().registerEvents(this,this); Objects.requireNonNull(getCommand("telixshop")).setExecutor(this); }
    private boolean hook(){try{Plugin p=Bukkit.getPluginManager().getPlugin("TaleWorldSMP"); if(p==null)return false; manager=p.getClass().getMethod("getCurrencyManager").invoke(p); Class<?> c=manager.getClass(); get=c.getMethod("get",Player.class,String.class);remove=c.getMethod("remove",Player.class,String.class,long.class);add=c.getMethod("add",Player.class,String.class,long.class);return true;}catch(Exception e){getLogger().warning("Core hook error: "+e);return false;}}
    private long bal(Player p){try{return ((Number)get.invoke(manager,p,"telix")).longValue();}catch(Exception e){return -1;}}
    private boolean take(Player p,long n){try{long b=bal(p);if(b<n)return false;remove.invoke(manager,p,"telix",n);return bal(p)<=b-n;}catch(Exception e){return false;}}
    private void refund(Player p,long n){try{add.invoke(manager,p,"telix",n);}catch(Exception ignored){}}
    public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)||!p.hasPermission("taleworldsmp.shop.use"))return true;main(p);return true;}
    private void main(Player p){Inventory i=Bukkit.createInventory(null,54,col(getConfig().getString("menu-title")));fill(i);item(i,20,Material.NETHERITE_SWORD,"&c⚔ Оружие и инструменты","&7Сильное снаряжение","&aНажмите, чтобы открыть");item(i,21,Material.SPAWNER,"&5✦ Спавнеры","&7Спавнеры и яйца","&aНажмите, чтобы открыть");item(i,22,Material.ORANGE_DYE,"&6&l🍂 Сезонные предметы","&eОсобая коллекция сезона","&aНажмите, чтобы открыть");item(i,29,Material.SHIELD,"&c⚔ PvP","&7Для сражений","&aНажмите, чтобы открыть");item(i,30,Material.ZOMBIE_HEAD,"&2☠ PvE","&7Против мобов","&aНажмите, чтобы открыть");item(i,31,Material.TNT,"&4💀 Для грифа","&7Рейды","&aНажмите, чтобы открыть");item(i,32,Material.HAY_BLOCK,"&e⛏ Фарм","&7Ресурсы","&aНажмите, чтобы открыть");item(i,33,Material.AMETHYST_SHARD,"&d✧ Артефакты","&7Редкие вещи","&aНажмите, чтобы открыть");item(i,49,Material.EMERALD,"&a&lTaleWorldSMP","&7Telix: &a"+bal(p));pages.put(p.getUniqueId(),"MAIN");p.openInventory(i);}
    private void page(Player p,String id){Inventory i=Bukkit.createInventory(null,54,col(id));fill(i);int[] s={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43};List<Product> ps=products(id);for(int n=0;n<ps.size()&&n<s.length;n++)i.setItem(s[n],display(ps.get(n)));item(i,45,Material.ARROW,"&a← Назад");item(i,49,Material.EMERALD,"&aTelix: &f"+bal(p));pages.put(p.getUniqueId(),id);p.openInventory(i);}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p))return;String id=pages.get(p.getUniqueId());if(id==null)return;e.setCancelled(true);if(e.getClickedInventory()!=e.getView().getTopInventory())return;int s=e.getRawSlot();if(id.equals("MAIN")){String x=switch(s){case 20->"WEAPONS";case 21->"SPAWNERS";case 22->"SEASONAL";case 29->"PVP";case 30->"PVE";case 31->"GRIEF";case 32->"FARM";case 33->"ARTIFACTS";default->null;};if(x!=null)page(p,x);return;}if(s==45){main(p);return;}int[] slots={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43};for(int n=0;n<slots.length;n++)if(slots[n]==s){List<Product> ps=products(id);if(n<ps.size())buy(p,ps.get(n));return;}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getWhoClicked() instanceof Player p&&pages.containsKey(p.getUniqueId()))e.setCancelled(true);}
    private void buy(Player p,Product x){if(bal(p)<x.price){p.sendMessage(col("&cНедостаточно Telix. Нужно &e"+x.price));return;}if(!take(p,x.price)){p.sendMessage(col("&cНе удалось списать Telix."));return;}if(!p.getInventory().addItem(x.item().clone()).isEmpty()){refund(p,x.price);p.sendMessage(col("&cНет места. Telix возвращены."));return;}p.sendMessage(col("&aКуплено: &f"+x.name+" &aза &e"+x.price+" Telix"));p.playSound(p.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,.7f,1.3f);page(p,pages.get(p.getUniqueId()));}
    private List<Product> products(String id){return switch(id){case "WEAPONS"->List.of(en(Material.NETHERITE_SWORD,"&cМеч Лорда вампиров",1899,6),en(Material.NETHERITE_PICKAXE,"&eКирка шахтёра",1599,7),en(Material.NETHERITE_AXE,"&6Громоруб",2199,6),en(Material.NETHERITE_SHOVEL,"&aЛопата Лесного стража",1699,6),en(Material.BOW,"&dЛук Звёздного охотника",1999,5),en(Material.CROSSBOW,"&4Арбалет Палача",1799,4),p(Material.TRIDENT,"&bТрезубец Нептуна",1499,1));case "SPAWNERS"->List.of(p(Material.SPAWNER,"&5Спавнер ×1",500,1),p(Material.SPAWNER,"&5Спавнер ×2",950,2),p(Material.SPAWNER,"&5Спавнер ×3",1350,3),p(Material.SPAWNER,"&5Спавнер ×4",1700,4),p(Material.SPAWNER,"&5Спавнер ×5",2000,5),p(Material.ZOMBIE_SPAWN_EGG,"&2Яйца зомби ×3",180,3),p(Material.SKELETON_SPAWN_EGG,"&7Яйца скелета ×3",240,3),p(Material.CREEPER_SPAWN_EGG,"&aЯйца крипера ×3",360,3),p(Material.ENDERMAN_SPAWN_EGG,"&5Яйца эндермена ×3",750,3),p(Material.BLAZE_SPAWN_EGG,"&6Яйца ифрита ×3",900,3),p(Material.WARDEN_SPAWN_EGG,"&3Яйца Вардена ×3",1800,3));case "SEASONAL"->List.of(en(Material.NETHERITE_SWORD,"&cКлинок Алого листопада",2999,7),p(Material.AMETHYST_SHARD,"&6Листопадный талисман",1099,1),p(Material.ENCHANTED_GOLDEN_APPLE,"&6Яблоко Последнего урожая",799,1),p(Material.POTION,"&cЗелье Багрового листа",899,1),p(Material.POTION,"&6Эликсир Тыквенной ночи",749,1),p(Material.POTION,"&3Настой Осеннего дождя",699,1),p(Material.POTION,"&8Отвар Увядшего леса",399,1),p(Material.POTION,"&5Эликсир Ночи Самайна",599,1),p(Material.POTION,"&cЗелье Алого тумана",649,1));case "PVP"->List.of(p(Material.GOLDEN_APPLE,"&cЗолотые яблоки ×4",299,4),p(Material.OBSIDIAN,"&5Обсидиан ×32",199,32),p(Material.ENDER_PEARL,"&dЭндер-жемчуг ×8",249,8),p(Material.END_CRYSTAL,"&bЭндер-кристалл ×4",399,4));case "PVE"->List.of(p(Material.GOLDEN_APPLE,"&6Золотые яблоки ×8",499,8),p(Material.ARROW,"&fСтрелы ×64",149,64),p(Material.TORCH,"&eФакелы ×64",99,64),p(Material.ENCHANTED_BOOK,"&aКнига Починки",999,1));case "GRIEF"->List.of(p(Material.TNT,"&cTNT ×16",199,16),p(Material.FLINT_AND_STEEL,"&8Огниво",149,1),p(Material.FIRE_CHARGE,"&6Огненный заряд ×8",249,8));case "FARM"->List.of(p(Material.COOKED_BEEF,"&cГовядина ×32",99,32),p(Material.CARROT,"&6Морковь ×64",49,64),p(Material.BONE,"&fКости ×64",79,64),p(Material.IRON_INGOT,"&fЖелезо ×16",199,16),p(Material.DIAMOND,"&bАлмазы ×8",599,8));default->List.of(p(Material.TOTEM_OF_UNDYING,"&eТалисман бессмертия",1199,1),p(Material.NETHER_STAR,"&fЗвезда Незера",1499,1),p(Material.ELYTRA,"&bЭлитры",2499,1),p(Material.SHULKER_BOX,"&dШалкеровый ящик",799,1));};}
    private Product p(Material m,String n,long price,int a){ItemStack i=new ItemStack(m,a);ItemMeta x=i.getItemMeta();if(x!=null){x.setDisplayName(col(n));i.setItemMeta(x);}return new Product(n,price,i);}
    private Product en(Material m,String n,long price,int lvl){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();if(x!=null){x.setDisplayName(col(n));String k=m==Material.BOW?"power":"sharpness";Enchantment z=Enchantment.getByKey(NamespacedKey.minecraft(k));if(z!=null)x.addEnchant(z,lvl,true);Enchantment u=Enchantment.UNBREAKING;if(u!=null)x.addEnchant(u,3,true);i.setItemMeta(x);}return new Product(n,price,i);}
    private ItemStack display(Product x){ItemStack i=x.item.clone();ItemMeta m=i.getItemMeta();if(m!=null){List<String> l=m.getLore()==null?new ArrayList<>():new ArrayList<>(m.getLore());l.add("");l.add(col("&7Цена: &a"+x.price+" Telix"));l.add(col("&eНажмите, чтобы купить"));m.setLore(l);i.setItemMeta(m);}return i;}
    private void item(Inventory i,int s,Material m,String n,String...l){i.setItem(s,icon(m,n,l));} private ItemStack icon(Material m,String n,String...l){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();if(x!=null){x.setDisplayName(col(n));x.setLore(Arrays.stream(l).map(this::col).toList());i.setItemMeta(x);}return i;} private void fill(Inventory i){ItemStack x=icon(Material.BLACK_STAINED_GLASS_PANE," ");for(int n=0;n<i.getSize();n++)i.setItem(n,x);} private String col(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);} private record Product(String name,long price,ItemStack item){}
}
